feather:
  permission: "feather.check"
  blocked-mods:
    - "zoom"
    - "timer"
    - "motion_blur"
    - "deathInfo"
    - "direction"
  discord:
    image-url: "https://example.com/server-icon.png"
    image-text: "Najlepszy serwer na świecie"
    state: "Dołącz teraz"
    details: "Gra teraz na survival"
  enabled-mods:
    - "item_physics"
    - "saturation"
    - "fps"
